/bond_disable_heartbeat_timeout: true
FollowPath.BaseObstacle.class: ObstacleFootprintCritic
FollowPath.BaseObstacle.scale: 5.0
FollowPath.BaseObstacle.sum_scores: true
FollowPath.GoalAlign.aggregation_type: last
FollowPath.GoalAlign.class: GoalAlign
FollowPath.GoalAlign.forward_point_distance: 0.1
FollowPath.GoalAlign.scale: 5.0
FollowPath.GoalDist.aggregation_type: last
FollowPath.GoalDist.class: GoalDist
FollowPath.GoalDist.scale: 5.0
FollowPath.Oscillation.class: Oscillation
FollowPath.Oscillation.oscillation_reset_angle: 0.2
FollowPath.Oscillation.oscillation_reset_dist: 0.05
FollowPath.Oscillation.oscillation_reset_time: -1.0
FollowPath.Oscillation.scale: 1.0
FollowPath.Oscillation.x_only_threshold: 0.05
FollowPath.PathAlign.aggregation_type: last
FollowPath.PathAlign.class: PathAlign
FollowPath.PathAlign.forward_point_distance: 0.1
FollowPath.PathAlign.scale: 5.0
FollowPath.PathDist.aggregation_type: last
FollowPath.PathDist.class: PathDist
FollowPath.PathDist.scale: 5.0
FollowPath.RotateToGoal.class: RotateToGoal
FollowPath.RotateToGoal.lookahead_time: -1.0
FollowPath.RotateToGoal.scale: 32.0
FollowPath.RotateToGoal.slowing_factor: 5.0
FollowPath.acc_lim_theta: 0.5
FollowPath.acc_lim_x: 0.5
FollowPath.acc_lim_y: 0.0
FollowPath.angular_granularity: 0.025
FollowPath.critics:
- RotateToGoal
- Oscillation
- BaseObstacle
- GoalAlign
- PathAlign
- PathDist
- GoalDist
FollowPath.debug_trajectory_details: true
FollowPath.decel_lim_theta: -0.5
FollowPath.decel_lim_x: -0.5
FollowPath.decel_lim_y: 0.0
FollowPath.default_critic_namespaces: []
FollowPath.discretize_by_time: false
FollowPath.forward_prune_distance: 2.0
FollowPath.include_last_point: true
FollowPath.linear_granularity: 0.05
FollowPath.marker_lifetime: 0.1
FollowPath.max_speed_xy: 0.4
FollowPath.max_vel_theta: 0.75
FollowPath.max_vel_x: 0.4
FollowPath.max_vel_y: 0.0
FollowPath.min_speed_theta: -0.75
FollowPath.min_speed_xy: -0.4
FollowPath.min_vel_x: -0.4
FollowPath.min_vel_y: 0.0
FollowPath.plugin: dwb_core::DWBLocalPlanner
FollowPath.prune_distance: 2.0
FollowPath.prune_plan: true
FollowPath.publish_cost_grid_pc: false
FollowPath.publish_evaluation: true
FollowPath.publish_global_plan: true
FollowPath.publish_local_plan: true
FollowPath.publish_trajectories: true
FollowPath.publish_transformed_plan: true
FollowPath.short_circuit_trajectory_evaluation: true
FollowPath.shorten_transformed_plan: true
FollowPath.sim_time: 4.0
FollowPath.time_granularity: 0.5
FollowPath.trajectory_generator_name: dwb_plugins::StandardTrajectoryGenerator
FollowPath.trans_stopped_velocity: 0.25
FollowPath.transform_tolerance: 0.2
FollowPath.vtheta_samples: 20
FollowPath.vx_samples: 20
FollowPath.vy_samples: 5
FollowPath.xy_goal_tolerance: 0.25
controller_frequency: 20.0
controller_plugins:
- FollowPath
failure_tolerance: 0.3
general_goal_checker.plugin: nav2_controller::SimpleGoalChecker
general_goal_checker.stateful: true
general_goal_checker.xy_goal_tolerance: 0.25
general_goal_checker.yaw_goal_tolerance: 0.25
goal_checker_plugins:
- general_goal_checker
min_theta_velocity_threshold: 0.001
min_x_velocity_threshold: 0.001
min_y_velocity_threshold: 0.5
odom_topic: odom
progress_checker.movement_time_allowance: 10.0
progress_checker.plugin: nav2_controller::SimpleProgressChecker
progress_checker.required_movement_radius: 0.5
progress_checker_plugin: progress_checker
speed_limit_topic: speed_limit
use_sim_time: false
